FROM php:5.6-apache

ENV MEMCACHED_VERSION 2.2.0

# Set up PHP and extensions
RUN apt-get update && apt-get install -y \
		git \
		libxml2-dev \
		mysql-client \
		libmemcached11 libmemcachedutil2 build-essential libmemcached-dev libz-dev \
		zlib1g-dev libicu-dev g++ \
		
	# Install mysql ext
	&& docker-php-ext-install -j$(nproc) mysqli \
	
	# Install igbinary
	&& pecl install igbinary \
	
	# Install memcached w/ igbinary support
	&& pecl download memcached-$MEMCACHED_VERSION \
	&& tar xzvf memcached-$MEMCACHED_VERSION.tgz \
	&& cd memcached-$MEMCACHED_VERSION \
	&& phpize \
	&& ./configure --enable-memcached-igbinary \
	&& make \
	&& make install \
    
	# Install intl ext
	&& docker-php-ext-configure intl \
	&& docker-php-ext-install intl \
    
	# Enable extensions
	&& docker-php-ext-enable mysqli intl igbinary memcached \
	
	# Get composer
	&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
	
	# Enable apache rewrite
	&& a2enmod rewrite \ 
	
	# Cleanup
	&& apt-get remove -y build-essential libmemcached-dev libz-dev libxml2-dev libicu-dev \
	&& apt-get autoremove -y \
	&& apt-get clean \
	&& rm -rf /tmp/pear \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/www/html/*

# Copy project files
WORKDIR /var/www
COPY htdocs /var/www/html
COPY . /var/www
RUN chown -R www-data:www-data *

# Debug
RUN yes | pecl install xdebug \
	&& echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini